### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Redduxx99** [royvds/assDialogueMerger#2]
Ran on a couple of files, worked for the first, ran into an error on the second

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\assdialoguemerger\cli.py", line 47, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\assdialoguemerger\cli.py", line 42, in main
    dialogue_merger.merge(base_file, dialogue_file,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\assdialoguemerger\assdialoguemerger.py", line 155, in merge
    event_changes = self.__find_events_misalignments(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\assdialoguemerger\assdialoguemerger.py", line 98, in __find_events_misalignments
    dialogue_sub.events[index+offset+iteration].text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ass\section.py", line 52, in __getitem__
    return self._lines[index]
IndexError: list index out of range
```

**Comment by rosvob** [comment]
I believe I know what the issue is, but just to be sure could you share the two .ass files that are causing the crash?

**Comment by LYS1THEA** [comment]
I encountered the same issue, so here are the [ass files I used](https://files.catbox.moe/n3qx8v.7z).
It seems to work only 1 way, i.e, assuming the folders I linked above:
```batch
C:\Users\username\Downloads>assdialoguemerger -bf base -df dialogue

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\assDialogueMerger.exe\__main__.py", line 7, in <module>
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\cli.py", line 42, in main
    dialogue_merger.merge(base_file, dialogue_file,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\assdialoguemerger.py", line 155, in merge
    event_changes = self.__find_events_misalignments(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\assdialoguemerger.py", line 85, in __find_events_misalignments
    dialogue_event = dialogue_sub.events[index+offset]
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\ass\section.py", line 52, in __getitem__
    return self._lines[index]
IndexError: list index out of range
```
If I flip the base and dialogue folder args, it works (assuming the folders I linked above).
```
assdialoguemerger -bf dialogue -df base
```

**Comment by rosvob** [comment]
> I encountered the same issue, so here are the [ass files I used](https://files.catbox.moe/n3qx8v.7z). It seems to work only 1 way, i.e, assuming the folders I linked above:

Branch style_regex has a fix for your particular use case, I will make a better fix once I get more time, hopefully this weekend.

**Comment by LYS1THEA** [comment]
i tried installing the other branch but i got this
```
C:\Users\USERNAME\Downloads\assDialogueMerger-style_regex>pip install .
WARNING: Ignoring invalid distribution miscfilters-obsolete- (c:\users\USERNAME\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution miscfilters-obsolete- (c:\users\USERNAME\appdata\roaming\python\python39\site-packages)
Processing c:\users\USERNAME\downloads\assdialoguemerger-style_regex
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):

          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']

      DESCRIPTION:
          `Project license <https://www.python.org/dev/peps/pep-0621/#license>`_.

      GIVEN VALUE:
          "GNU General Public License v3 (GPLv3)"

      OFFENDING RULE: 'oneOf'

      DEFINITION:
          {
              "oneOf": [
                  {
                      "properties": {
                          "file": {
                              "type": "string",
                              "$$description": [
                                  "Relative path to the file (UTF-8) which contains the license for the",
                                  "project."
                              ]
                          }
                      },
                      "required": [
                          "file"
                      ]
                  },
                  {
                      "properties": {
                          "text": {
                              "type": "string",
                              "$$description": [
                                  "The license of the project whose meaning is that of the",
                                  "`License field from the core metadata",
                                  "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                              ]
                          }
                      },
                      "required": [
                          "text"
                      ]
                  }
              ]
          }
      Traceback (most recent call last):
        File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 126, in read_configuration
          validate(subset, filepath)
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-b6eg169y\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 51, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.license`.
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):

          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution miscfilters-obsolete- (c:\users\USERNAME\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution miscfilters-obsolete- (c:\users\USERNAME\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution miscfilters-obsolete- (c:\users\USERNAME\appdata\roaming\python\python39\site-packages)

C:\Users\USERNAME\Downloads\assDialogueMerger-style_regex>assdialoguemerger
'assdialoguemerger' is not recognized as an internal or external command,
operable program or batch file.
```
