### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LYS1THEA** [royvds/assDialogueMerger#5]
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\assDialogueMerger.exe\__main__.py", line 7, in <module>
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\cli.py", line 46, in main
    dialogue_merger.merge(base_file, dialogue_file,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\assdialoguemerger.py", line 157, in merge
    event_changes = self.__find_events_misalignments(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\assdialoguemerger\assdialoguemerger.py", line 100, in __find_events_misalignments
    dialogue_sub.events[index+offset+iteration].text)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\ass\section.py", line 52, in __getitem__
    return self._lines[index]
IndexError: list index out of range
```
[Ass files i used](https://github.com/royvds/assDialogueMerger/files/9687232/test.zip)

I got around this by adding `^Flashback` [here](https://github.com/royvds/assDialogueMerger/blob/main/assdialoguemerger/assdialoguemerger.py#L56).
A possible fix might be an optional argument like `-regex "^Flashback"` .

**Comment by rosvob** [comment]
Yes, this option exists since I solved the previous issue, -f (--filter) allows you to set a custom regex. Make sure to reinstall / update your install first.

**Comment by LYS1THEA** [comment]
Oh right! thanks!
